# almalinux is exactly same as redhat image, but completetely free to use. 
FROM almalinux:9
LABEL COURSE="Docker" \
        TRAINER="Jaya" \
        DURATION="10HRS" \
        AUTHOR="Jayadevops" 
        
